project:
  type: website
  output-dir: docs
  resources:
    - "*.mp4"
    - "*.wasm"

website:
  title: "Madiyar's Page"
  site-url: https://maitbayev.github.io
  description: "Madiyar's Page"
  google-analytics: "G-XDL07RCJG6"
  navbar:
    left:
      - text: "ESL"
        href: esl
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: substack
        href: https://maitbayev.substack.com/subscribe
      - icon: telegram
        href: https://t.me/swemanml
format:
  html:
    theme: cosmo
    css: styles.css



